### ISSUE TITLE
Fails when proxied url contains protocol

### ISSUE THREAD

**Issue by davewilton** [chrishoage/gulp-connect-proxy#1]
If the proxied url contains the protocol it won't proxy the url. For example:

This works:

http://localhost:8080/proxy/lh4.ggpht.com/wKrDLLmmxjfRG2-E-k5L5BUuHWpCOe4lWRF7oVs1Gzdn5e5yvr8fj-ORTlBF43U47yI=w300

however, this does not

http://localhost:8080/proxy/http://lh4.ggpht.com/wKrDLLmmxjfRG2-E-k5L5BUuHWpCOe4lWRF7oVs1Gzdn5e5yvr8fj-ORTlBF43U47yI=w300

Is this expected behaviour?

**Comment by chrishoage** [comment]
Sorry somehow missed this ticket. 

Yes, `http` is hard coded into the proxy. As this is a simple tool for development purposes I have no plans to support SSL.

**Comment by davewilton** [comment]
Chris,
  Trouble is my real proxy requires the protocol to be sent with it. A simple check to see if the protocol exists before appending would do the trick. Will submit a pull request for you to consider

**Comment by chrishoage** [comment]
I'm not sure I follow. What this plugin does is make a request to a url. I wanted to avoid having to URL Encode the URL which if one were to include the protocol it would have to be URL encoded. 

If you are using a proxy in production I suggest figuring out a way to have that proxy work in development as it will closer match your real world code.
